### ISSUE TITLE
Add a remove_node helper

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/syn#1]
In case a node is permanently removed from a cluster, allow to remove it from the underlying mnesia database db_nodes.

**Comment by kevinwilson541** [comment]
Hey @ostinelli, I can help out with this. My understanding of this would mean that in `syn_consistency`, a `handle_info` handler would need to be added that would call `mnesia:del_table_copy` on the external node being removed from the cluster.

Only question I have is how to detect that permanent removal state. Should that be handled by the outside application using syn, where this `remove_node` handler is explicitly triggered? Or some failure detection scenario using pings against the set of nodes in the cluster?

**Comment by ostinelli** [comment]
Closing as unneeded in v2.
