### ISSUE TITLE
connection between nodes

### ISSUE THREAD

**Issue by lang100** [ostinelli/syn#34]
hi,
Trying to get started with syn, but it doesn't seem to work :
I have two node in my machine (`foo@my-pc` and `bar@my-pc`).  
in `foo` i have a simple genserver that is started with this name : `{:via, :syn, :example_server}`,
and handles a `:get` call.  
running : `GenServer.whereis({:via, :syn, :example_server})`  
gives me the pid.    
My problem is in `bar`:    
I connected the nodes :  
Node.connect :'foo@my-pc'  
And than tried running `GenServer.whereis({:via, :syn, :example_server})`  
but i get `nil`  
and of course `GenServer.call({:via, :syn, :example_server}, :get)` doesn't work :(
What am i missing ?

**Comment by cystbear** [comment]
👍   same for me there

I'll create separate issue with Erlang code inside, but not Elixir.

**Comment by cystbear** [comment]
Hey @lang100 take a look https://github.com/ostinelli/syn/issues/35#issuecomment-310065548

**Comment by ostinelli** [comment]
There isn't enough information for me to provide feedback. Please see if your configurations are correct, including the one @cystbear refers to.
