### ISSUE TITLE
Registering processes timing out

### ISSUE THREAD

**Issue by cookkkie** [ostinelli/syn#37]
Hi,

I do have to register 2k processes (sometimes more) at the exact same time. And sometimes `join/2` was timing out. Is there a solution about that?

Thanks.

UPDATE: I just saw your blog post with the syn benchmark. I don't understand why I cannot achieve that. Registry messages keep getting stuck in the :syn_groups genserver. The only possible reason I could find is that I also heavily do :mnesia inserts, maybe it is slowing down mnesia? (doing something like 15M inserts in a 30 minutes frame)

UPDATE2:
So to avoid the timeout thing, I forked the project and added `async_join` just to see how fast it would add the processes to the group.
The :syn_groups genserver went up to 120k (I have something like 330k processes to add to the group) join messages in its mailbox and took approx. 30 minutes to handle them all. It was mostly hanging on :mnesia functions. Feels like the :bag type table is just slow.

**Comment by ostinelli** [comment]
Hi @cookkkie did you manage to solve what you were experiencing?

**Comment by cookkkie** [comment]
Yeah, basically I partitioned the :syn_registry and :syn_groups. 1 per scheduler. It works well better now 👌
