### ISSUE TITLE
Feature request (group count)

### ISSUE THREAD

**Issue by tommysrn** [ostinelli/syn#40]
Just like process registries have a `syn:registry_count()` and `syn:registry_count(Node)`, would it be possible to have something similar for groups (get the total number of groups and number of local groups)?
I'm wondering if there's a way to do that without impacting performance (maybe adding counters somewhere).
If you point me in the right direction I could also look at how to implement this myself. Thank you!

**Comment by tommysrn** [comment]
Just adding some notes: `mnesia:table_info(syn_groups_table, size).` could be used but I'm not sure if you use table fragmentation.

**Comment by vkatsuba** [comment]
Hi @ostinelli,

Here is PR https://github.com/ostinelli/syn/pull/46 for `syn:groups_count/0 and `syn:groups_count/1`

Best Regards,
--V

**Comment by ostinelli** [comment]
Implemented in 65dc15493fbf2363f1a144803672c2c64be9f260. Will be included in `2.1.0`.
