### ISSUE TITLE
Does a GenServer register itself after restart in case of a crash?

### ISSUE THREAD

**Issue by egze** [ostinelli/syn#51]
We are using Swarm now and it has an issue that if a registered pid dies and restarted by a supervisor, then it is not registered anymore. See https://github.com/bitwalker/swarm/issues/6

How does Syn deal with it?

**Comment by egze** [comment]
Also, does Syn automatically restart processes on a new node if topology changes and the current node goes down?

**Comment by ostinelli** [comment]
Syn uses the `{via,Module,ViaName}` server reference to register processes. What happens after that is in the hands of Erlang. Have you tried it yourself?
