### ISSUE TITLE
syn:join fails for some Names

### ISSUE THREAD

**Issue by fycth** [ostinelli/syn#6]
You claim that Name is any(), but there is an issue:

```
syn:join({"topic",1212},self()).

** {{aborted,{badarg,[syn_pg_table,
                      [{{syn_pg_table,'$1','$2','_'},
                        [{'=:=','$1',{"topic",1212}},{'=:=','$2',<0.878.0>}],
                        ['$2']}]]}},
```

I fixed this by using term_to_binary:

```
syn:join(term_to_binary({topic,"1212"}),self()).
ok
```

I am not sure how to fix this. Would it be OK to just wrapping Name with term_to_binary? Or the possible solution lies deeper in the code?

**Comment by ostinelli** [comment]
Thank you @fycth, this has also been reported by @5HT in his [tweet](https://twitter.com/5HT/status/706243083923488768).

This is fixed in 0c4096b87cf883840c30987a304da700520aad39.
