### ISSUE TITLE
Add time to CustomEventHandler:resolve_registry_conflict

### ISSUE THREAD

**Issue by alesasnouski** [ostinelli/syn#64]
Custom resolve_registry_conflict function can also rely on Time.
Can we extend (Name, {Pid1, Meta1}, {Pid2, Meta2}) tuples with Time like in do_resolve_registry_conflict :
Name, {Pid1, Meta1, Time1}, {Pid2, Meta2, Time2} ?

**Comment by ostinelli** [comment]
Yes, and in fact this is how `v3` handles it:
https://github.com/ostinelli/syn/blob/v3/src/syn_event_handler.erl#L99

`v2` is frozen, I'll need a little time to complete the new version before it becomes available. That said, time is obviously a far from perfect resolution variable in a distribution environment, but it's the one we've got..
