### ISSUE TITLE
Support registering metadata in via-tuples

### ISSUE THREAD

**Issue by ahovgaard** [ostinelli/syn#67]
I would like to suggest extending the via-tuple support to allow registering metadata as well. This would enable one to do as follows:
```elixir
iex> tuple = {:via, :syn, {:devices, "SN-123-456789", [meta: :one]}}
{:via, :syn, {:devices, "SN-123-456789", [meta: :one]}}
iex> GenServer.start_link(__MODULE__, [], name: tuple)
{ok, #PID<0.105.0>}
iex> :syn.lookup(:devices, "SN-123-456789")
{#PID<0.105.0>, [meta: :one]}
```

For reference, registering a value in a via-tuple is already supported by the Elixir Registry, see: https://hexdocs.pm/elixir/1.12/Registry.html#module-using-in-via

If this feature is considered appropriate and useful, I would like to implement it and make a PR with the changes.

**Comment by ostinelli** [comment]
Sounds good! I'd be happy to review & merge in.

**Comment by ostinelli** [comment]
This is now in `3.2.1`.
