### ISSUE TITLE
whereis_name/2 export is missing on syn.erl

### ISSUE THREAD

**Issue by immnas** [ostinelli/syn#71]
whereis_name/2 export is missing on syn.erl ..
its says undefined.

**Comment by ostinelli** [comment]
What says it?

`whereis_name/2` is an internal method on `syn`. Compatible registries that use the `via` module notation only need [`whereis_name/1`](https://www.erlang.org/doc/man/global.html#whereis_name-1) AFAIK, which is exported [here](https://github.com/ostinelli/syn/blob/3.2.2/src/syn.erl#L68).

Can you provide clarity on what you are doing and trying to achieve?

**Comment by immnas** [comment]
Hi,

I am calling syn:add_node_to_scopes([device]).
then i am checking syn:whereis_name(device,Key).

**Comment by ostinelli** [comment]
Well you shouldn't. Docs are pretty clear, use [lookup/2](https://hexdocs.pm/syn/syn.html#lookup/2).

**Comment by immnas** [comment]
okay sorry i missed that. if i have send message to that PID. do i have to use some other API.
