### ISSUE TITLE
What solution use instead syn.unregister_and_register?

### ISSUE THREAD

**Issue by dziaineka** [ostinelli/syn#72]
Hello.

Syn version 2.* had `syn.unregister_and_register` function to make this operations atomic. Is it plans to make the same function in Syn 3.0 or another solution exists?

Thank you for your work!

**Comment by ostinelli** [comment]
This operation was not atomic, as it would still need the propagation to happen to the rest of the cluster. Rather, this helper method allowed to avoid a potential `{error, taken}` response to a registration call issued immediately after an unregistration call while waiting for the propagation to happen.

Syn v3 has different internals: when registering / unregistering a process the local database is updated immediately, so there's no need to wait for propagation. If you're curious see [here](https://github.com/ostinelli/syn/blob/3.3.0/src/syn_registry.erl#L121).

Therefore you can just call `unregister/2` and then `register/3,4` sequentially to achieve the same effect.
