### ISSUE TITLE
The consistency of group membership

### ISSUE THREAD

**Issue by erlmachinedev** [ostinelli/syn#75]
Hi @ostinelli, I found this case which would be nice to classify first (before more detailed test and clarification).

```erlang
syn:is_member/3
```

```erlang
syn:members/2
```

The first call makes the negative `false` until `syn:members/2` invocation has done from the client side. 

**It seems that the second call ensures the consistency while the first one doesn't.** 

If so (`is_member/3` isn't consistent by nature) the right [doc](https://hexdocs.pm/syn/syn.html#is_member/3) could be done (to describe the feature properly).

If not (there is a bug 🐛) maybe I could help (at least to give more info and try to reproduce via ct test).

What do you think?

Best regards, Slava

**Comment by ostinelli** [comment]
Both calls check the local ETS tables, there is no difference between the two calls (besides the return values).

Also, syn is eventually consistent.

**Comment by erlmachinedev** [comment]
Thanks for the instant answer @ostinelli, maybe some issue with my ct SUITE. If there are both perform ETS query then probably issue on my side.
